import { Bebas_Neue, Space_Grotesk } from "next/font/google";
import "./globals.css";

const heading = Bebas_Neue({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400"
});

const body = Space_Grotesk({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "700"]
});

export const metadata = {
  title: "DevilMaxy Guild Chat",
  description: "Discord-style chat for subscribers and Free Fire guild mates"
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '../components/Sidebar';
import MobileNav from '../components/MobileNav';
import { UserProvider } from '../components/UserContext';
import geminiImage from '../Gemini_Generated_Image_.png';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> ee991a1 (Initial commit from Create Next App)
import { Bebas_Neue, Space_Grotesk } from "next/font/google";
import "./globals.css";

const heading = Bebas_Neue({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400"
});

const body = Space_Grotesk({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "700"]
});

export const metadata = {
  title: "DevilMaxy Guild Chat",
  description: "Discord-style chat for subscribers and Free Fire guild mates"
=======
  title: "Devilmaxy Hub",
  description: "Glass-themed social hub for chat, guilds, DMs, profile, and admin tools.",
>>>>>>> c59a53a (Update project files)
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
<<<<<<< HEAD
    <html lang="en">
      <body className={`${heading.variable} ${body.variable}`}>{children}</body>
    <html lang="en">
      <body className={`${heading.variable} ${body.variable}`}>{children}</body>
=======
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full relative overflow-x-hidden text-slate-100">
        {/* Background image */}
        <div
          className="fixed inset-0 z-0 bg-cover bg-center opacity-20"
          style={{
            backgroundImage: `url(${geminiImage.src})`,
            filter: 'blur(3px) saturate(115%)'
          }}
        />
        <div className="relative z-10 flex min-h-screen gap-5 p-4 lg:p-6">
          <UserProvider>
            <Sidebar />
            <main className="glass-shell flex-1 min-h-[calc(100vh-2rem)] lg:min-h-[calc(100vh-3rem)] p-4 pb-24 lg:p-8 lg:pb-8 relative overflow-hidden">
              {children}
            </main>
            <MobileNav />
          </UserProvider>
        </div>
      </body>
>>>>>>> c59a53a (Update project files)
    </html>
  );
}
